Create TABLE PERSON
(
PERSON_ID BIGINT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT "ID of person for reference",
FIRST_NAME CHAR(50) NULL COMMENT "Person's legal first name at birth",
LAST_NAME CHAR(50) NULL COMMENT "Person's legal family name at birth",
MAIDEN_NAME CHAR(50) NULL COMMENT "Person's family name before getting mirried",
MIDDLE_NAMES CHAR(250) NULL COMMENT "Person's middle name",
ALLIS CHAR(12) NULL COMMENT "Person's nickname",
DOB  DATE NOT NULL COMMENT "Date of Birth",
DOD DATE NULL COMMENT "Date of Death",
SEX ENUM ('male', 'female', 'other') NULL COMMENT "Person's sex at birth"
);

Create TABLE PARENT
(
CHILD_ID BIGINT UNSIGNED ZEROFILL NOT NULL,
PARENT_ID BIGINT UNSIGNED ZEROFILL NOT NULL,
TYPE ENUM ('mother', 'father'),
PRIMARY KEY (CHILD_ID, PARENT_ID),
FOREIGN KEY (PARENT_ID) REFERENCES PERSON(PERSON_ID),
FOREIGN KEY (CHILD_ID) REFERENCES PERSON(PERSON_ID)
);
