Create TABLE PERSON
(
PERSON_ID CHAR(12) NOT NULL PRIMARY KEY COMMENT "ID of person for reference",
FIRST_NAME CHAR(50) NULL COMMENT "Person's legal first name at birth",
LAST_NAME CHAR(50) NULL COMMENT "Person's legal family name at birth",
MAIDEN_NAME CHAR(50) NULL COMMENT "Person's family name before getting mirried",
MIDDLE_NAMES CHAR(250) NULL COMMENT "Person's middle name",
ALLIS CHAR(12) NULL COMMENT "Person's nickname",
DOB  DATE NULL COMMENT "Date of Birth",
DOD DATE NULL COMMENT "Date of Death",
SEX ENUM ('male', 'female', 'other') NULL COMMENT "Person's sex at birth",
COD VARCHAR(100) NULL COMMENT "Cause of Death",
FACEBOOKID VARCHAR(20) NULL COMMENT "Facebook id"
);

Create TABLE PARENT
(
CHILD_ID CHAR(12) NOT NULL,
PARENT_ID CHAR(12) NOT NULL,
TYPE ENUM ('mother', 'father'),
PRIMARY KEY (CHILD_ID, PARENT_ID),
FOREIGN KEY (PARENT_ID) REFERENCES PERSON(PERSON_ID),
FOREIGN KEY (CHILD_ID) REFERENCES PERSON(PERSON_ID)
);

Create Table PARTNER
(
PERSON_1_ID CHAR(12) NOT NULL,
PERSON_2_ID CHAR(12) NOT NULL,
PLACE CHAR(250) NULL,
DATE DATE NULL,
PRIMARY KEY(PERSON_1_ID,PERSON_2_ID),
FOREIGN KEY(PERSON_1_ID) REFERENCES PERSON(PERSON_ID),
FOREIGN KEY(PERSON_2_ID) REFERENCES PERSON(PERSON_ID)
);
